[[conclusion_chapter]]
== 結論

(((「閃電網路中的創新」, id="ix_17_conclusion-asciidoc0", range="startofrange")))在短短幾年內，閃電網路已從一篇白皮書發展成為一個快速成長的全球網路。作為比特幣的第二層，它實現了快速、低成本和私密支付的承諾。此外，它還引發了一場創新海嘯，將開發人員從比特幣開發中存在的同步共識限制中解放出來。

閃電網路的創新正在多個不同層面發生：

* 在比特幣核心協定層面，為新的比特幣腳本操作碼、簽名演算法和最佳化提供使用需求
* 在閃電協定層面，新功能在全網快速部署
* 在支付通道層面，有新的通道結構和增強功能
* 作為獨立的可選功能，由獨立實作端對端部署，發送者和接收者可以按需使用
* 在客戶端和協定之上構建新穎且令人興奮的閃電應用程式（LApps）

讓我們來看看這些創新如何在現在和不久的將來改變閃電網路。

=== 去中心化和非同步創新

(((「閃電網路中的創新」,「去中心化/非同步特性」)))閃電網路不受同步共識的約束，這與比特幣不同。這意味著不同的閃電客戶端可以實作不同的功能並協商它們的互動（參見 <<feature_bits>>）。因此，閃電網路的創新速度比比特幣快得多。

閃電網路不僅在快速發展，而且正在為比特幣系統創造對新功能的需求。比特幣中許多近期和計劃中的創新都是因為它們在閃電網路中的使用而產生動機和理由。事實上，閃電網路經常被提及作為許多新功能的範例使用案例。

[[bitcoin_prot_17]]
==== 比特幣協定和比特幣腳本創新

(((「比特幣（系統）」,「由閃電網路使用案例推動的創新」)))(((「比特幣腳本」,「由閃電網路使用案例推動的創新」)))(((「閃電網路中的創新」,「由閃電網路使用案例推動的比特幣創新」)))比特幣系統在本質上是一個保守的系統，必須保持與共識規則的相容性，以避免區塊鏈的意外分叉或 P2P 網路的分裂。因此，新功能在實作到主網（實際運行的生產系統）之前需要大量的協調和測試。

以下是一些當前或提議中由閃電網路使用案例推動的比特幣創新：

Neutrino:: 一種輕量級客戶端協定，與傳統的 SPV 協定相比具有改進的隱私功能。Neutrino 主要被閃電客戶端用來存取比特幣區塊鏈。

Schnorr 簽名:: 作為 _Taproot_ 軟分叉的一部分引入，Schnorr 簽名將使閃電網路中的靈活點時間鎖定合約（PTLCs）成為可能用於通道建構。這可能特別會使用可撤銷簽名而不是可撤銷交易。

Taproot:: 也是 2021 年 11 月引入 Schnorr 簽名的軟分叉的一部分，Taproot 允許複雜的腳本看起來像單一付款人、單一收款人的支付，與比特幣上最常見的支付類型無法區分。這將使閃電通道的協作（相互）關閉交易看起來與簡單支付無法區分，並增強閃電網路使用者的隱私。

輸入重新綁定:: 也被稱為 SIGHASH_NOINPUT 或 SIGHASH_ANYPREVOUT，這個計劃中的比特幣腳本語言升級主要是由高級智慧合約（如 eltoo 通道協定）所推動。

契約（Covenants）:: 目前處於研究的早期階段，契約允許交易建立輸出，以限制未來花費這些輸出的交易。這種機制可以通過在承諾交易中強制執行地址白名單來提高閃電通道的安全性。

==== 閃電協定創新

(((「閃電網路中的創新」,「閃電 P2P 協定」)))(((「閃電網路協定」,「創新」)))閃電 P2P 協定具有高度可擴展性，自其誕生以來已經歷了大量變化。功能位元中使用的「奇數也可以」規則（參見 <<feature_bits>>）確保節點可以協商它們支援的功能，從而實現協定的多個獨立升級。

==== TLV 可擴展性

(((「閃電網路中的創新」,「TLV 可擴展性」)))(((「類型-長度-值（TLV）格式」,「創新」)))類型-長度-值（參見 <<tlv>>）擴展訊息協定的機制非常強大，已經在保持向前和向後相容性的同時，實現了閃電網路中多項新功能的引入。
一個突出的範例是正在開發中的路徑盲化和蹦床支付，它允許接收者對發送者隱藏自己，同時也允許行動客戶端在不需要在設備上儲存完整通道圖的情況下發送支付，透過使用第三方來實現，而且不需要向該第三方透露最終接收者。

==== 支付通道建構

(((「閃電網路中的創新」,「支付通道建構」)))(((「支付通道」,「建構創新」)))支付通道是由兩個通道夥伴運營的抽象概念。只要這兩方願意運行新程式碼，他們就可以同時實作各種通道機制。事實上，最近的研究表明，通道甚至可以動態升級到新機制，而無需關閉舊通道並開啟新類型的通道。

eltoo:: 一種提議的通道機制，使用輸入重新綁定來顯著簡化支付通道的操作，並消除對懲罰機制的需求。它需要一種新的比特幣簽名類型才能實作。

==== 可選的端對端功能

(((「閃電網路中的創新」,「可選的端對端功能」)))點時間鎖定合約（PTLCs）:: 一種不同於 HTLC 的方法，PTLC 可以增強隱私、減少洩露給中間節點的資訊，並且比基於 HTLC 的通道運作更有效率。

大型通道:: 大型或 _Wumbo_ 通道以動態方式引入網路，無需協調。支援大額支付的通道作為通道公告訊息的一部分進行廣播，可以以可選方式使用。

多部分支付（MPP）:: MPP 也是以可選方式引入的，更棒的是它只需要支付的發送者和接收者能夠使用 MPP。網路的其餘部分只需像路由單一部分支付一樣路由 HTLC。

JIT 路由:: 一種可選方法，可被路由節點用來提高其可靠性並保護自己免受垃圾訊息攻擊。

Keysend:: 由閃電客戶端實作獨立引入的升級，它允許發送者以「主動」和非同步的方式發送資金，而無需事先取得發票。

HODL 發票footnote:[_HODL_ 這個詞來自論壇中一個興奮的拼寫錯誤，將 "HOLD"（持有）誤拼，用來鼓勵人們不要在恐慌中出售比特幣。]:: 最終 HTLC 不被收取的支付，使發送者承諾該支付，但允許接收者延遲收取直到滿足某些其他條件，或在不收取的情況下取消發票。這也是由不同的閃電客戶端獨立實作的，可以以可選方式使用。

洋蔥路由訊息服務:: 洋蔥路由機制和節點的底層公鑰資料庫可用於發送與支付無關的資料，例如文字訊息或論壇貼文。使用閃電網路實現付費訊息作為解決垃圾貼文和女巫攻擊（垃圾訊息）的方案，是另一項獨立於核心協定實作的創新。

Offers:: 目前作為 BOLT #12 提議但已被某些節點實作，這是一種通訊協定，用於透過洋蔥訊息從遠端節點請求（週期性）發票。

[[lapps]]
=== 閃電應用程式（LApps）

(((「閃電網路中的創新」,「閃電應用程式」)))(((「閃電應用程式（LApps）」)))雖然仍處於起步階段，我們已經看到有趣的閃電應用程式開始出現。廣義上定義為使用閃電協定或閃電客戶端作為組件的應用程式，LApps 是閃電網路的應用層。
一個突出的範例是 LNURL，它提供與 BOLT #12 offers 類似的功能，但是透過 HTTP 和閃電地址實現。它在 offers 之上運作，為使用者提供類似電子郵件風格的地址，其他人可以向該地址發送資金，而軟體在背景向節點的 LNURL 端點請求發票。
更多的 LApps 正在為簡單遊戲、訊息應用程式、微服務、可付費 API、付費自動販賣機（例如加油機）、衍生品交易系統等建構。

=== 準備就緒，出發！

未來看起來一片光明。閃電網路正在將比特幣帶入新的未探索市場和應用領域。憑藉本書中的知識，你可以探索這個新疆界，甚至可能作為先驅者加入，開闢一條新路徑。(((range="endofrange", startref="ix_17_conclusion-asciidoc0")))
